Attribute VB_Name = "modConsolidate"
'==============================================================================
' modConsolidate - Daily Data Consolidation Module
' APP Billing System
'
' Reads all user daily files for a given date and merges them into a single
' consolidated Excel file for reporting and data management.
'==============================================================================
Option Explicit

'------------------------------------------------------------------------------
' ConsolidateDailyData - Merges all user files for a date into one workbook
'
' Parameters:
'   dtDate - The date to consolidate
'
' Returns: Full path to the consolidated file, or empty string on failure
'------------------------------------------------------------------------------
Public Function ConsolidateDailyData(ByVal dtDate As Date) As String
    On Error GoTo ErrHandler

    If Not IsNetworkAvailable() Then
        MsgBox "Network share is not available. Cannot consolidate data.", _
               vbExclamation, "Network Unavailable"
        ConsolidateDailyData = ""
        Exit Function
    End If

    ' Get all user files for this date
    Dim colFiles As Collection
    Set colFiles = GetUserFilesForDate(dtDate)

    If colFiles.Count = 0 Then
        MsgBox "No data files found for " & Format(dtDate, "DD/MM/YYYY") & ".", _
               vbInformation, "No Data"
        ConsolidateDailyData = ""
        Exit Function
    End If

    ' Create the consolidated workbook
    Dim wbOut As Workbook
    Set wbOut = Workbooks.Add(xlWBATWorksheet)

    Dim wsOut As Worksheet
    Set wsOut = wbOut.Sheets(1)
    wsOut.Name = "AllUsers_" & Format(dtDate, "YYYYMMDD")

    ' Write headers
    Dim headers As Variant
    headers = Array("S #", "Anesthesiologist", "Site", "Date of Service", _
                    "Shift Name", "On Call", "Shift Type", "Surgical Procedure Code", _
                    "Procedure Start Time", "Procedure Finish Time", "Maximum IC Level", _
                    "Consults", "Fee Modifier 1", "Fee Modifier 2", "Fee Modifier 3", _
                    "Resuscitation", "Obstetrics", "Acute Pain", _
                    "Diagnostic and Chronic Pain", "Miscellaneous Fee Items", _
                    "WCB Number", "Side", "Diagnostic Code", "Injury Code", _
                    "Date of Injury", "Submitted By", "Submitted On", "Source File")

    Dim j As Long
    For j = 0 To UBound(headers)
        wsOut.Cells(1, j + 1).Value = headers(j)
    Next j

    ' Format headers
    With wsOut.Range(wsOut.Cells(1, 1), wsOut.Cells(1, UBound(headers) + 1))
        .Font.Bold = True
        .Interior.Color = RGB(68, 114, 196)
        .Font.Color = RGB(255, 255, 255)
        .AutoFilter
    End With

    ' Process each file
    Dim lOutRow As Long
    lOutRow = 2

    Dim lFileCount As Long
    lFileCount = 0

    Application.ScreenUpdating = False
    Application.StatusBar = "Consolidating data..."

    Dim sFile As Variant
    For Each sFile In colFiles
        lFileCount = lFileCount + 1
        Application.StatusBar = "Processing file " & lFileCount & " of " & colFiles.Count & "..."

        Dim wbIn As Workbook
        Set wbIn = Workbooks.Open(CStr(sFile), ReadOnly:=True, UpdateLinks:=0)

        Dim wsIn As Worksheet
        Set wsIn = wbIn.Sheets(1)

        Dim lastRow As Long
        lastRow = wsIn.Cells(wsIn.Rows.Count, COL_ANESTH).End(xlUp).Row

        ' Copy each data row
        Dim i As Long
        For i = 2 To lastRow
            ' Copy columns A through AA
            For j = 1 To COL_SUBMON
                wsOut.Cells(lOutRow, j).Value = wsIn.Cells(i, j).Value
            Next j

            ' Re-number the serial
            wsOut.Cells(lOutRow, COL_SERIAL).Value = lOutRow - 1

            ' Add source file reference (column AB in consolidated = 28)
            Dim sFileName As String
            sFileName = Mid(CStr(sFile), InStrRev(CStr(sFile), "\") + 1)
            wsOut.Cells(lOutRow, 28).Value = sFileName

            lOutRow = lOutRow + 1
        Next i

        wbIn.Close SaveChanges:=False
    Next sFile

    ' Auto-fit columns
    wsOut.Columns.AutoFit

    ' Add summary info
    Dim wsSummary As Worksheet
    Set wsSummary = wbOut.Sheets.Add(After:=wsOut)
    wsSummary.Name = "Summary"

    wsSummary.Cells(1, 1).Value = "APP Billing - Daily Consolidation Report"
    wsSummary.Cells(1, 1).Font.Bold = True
    wsSummary.Cells(1, 1).Font.Size = 14

    wsSummary.Cells(3, 1).Value = "Date:"
    wsSummary.Cells(3, 2).Value = Format(dtDate, "DD/MM/YYYY")

    wsSummary.Cells(4, 1).Value = "Generated:"
    wsSummary.Cells(4, 2).Value = FormatTimestamp(Now)

    wsSummary.Cells(5, 1).Value = "Generated By:"
    wsSummary.Cells(5, 2).Value = Application.UserName

    wsSummary.Cells(6, 1).Value = "Files Processed:"
    wsSummary.Cells(6, 2).Value = colFiles.Count

    wsSummary.Cells(7, 1).Value = "Total Records:"
    wsSummary.Cells(7, 2).Value = lOutRow - 2

    wsSummary.Range("A3:A7").Font.Bold = True
    wsSummary.Columns("A:B").AutoFit

    ' Save the consolidated file
    Dim sOutPath As String
    sOutPath = GetNetworkPath() & FOLDER_DAILY_EXPORTS & "\"
    CreateFolderIfNotExists sOutPath
    sOutPath = sOutPath & "AllUsers_" & Format(dtDate, "YYYYMMDD") & ".xlsx"

    Application.DisplayAlerts = False
    wbOut.SaveAs sOutPath, FileFormat:=xlOpenXMLWorkbook
    Application.DisplayAlerts = True

    ' Close the output workbook after saving
    wbOut.Close SaveChanges:=False

    Application.StatusBar = False
    Application.ScreenUpdating = True

    ConsolidateDailyData = sOutPath
    Exit Function

ErrHandler:
    Application.StatusBar = False
    Application.ScreenUpdating = True
    Application.DisplayAlerts = True
    On Error Resume Next
    If Not wbIn Is Nothing Then wbIn.Close SaveChanges:=False
    If Not wbOut Is Nothing Then wbOut.Close SaveChanges:=False
    MsgBox "Error during consolidation: " & Err.Description, vbCritical, "Consolidation Error"
    ConsolidateDailyData = ""
End Function

'------------------------------------------------------------------------------
' ConsolidateDateRange - Consolidates data for a range of dates
'
' Parameters:
'   dtStart - Start date
'   dtEnd   - End date
'
' Returns: Path to the consolidated file
'------------------------------------------------------------------------------
Public Function ConsolidateDateRange(ByVal dtStart As Date, ByVal dtEnd As Date) As String
    On Error GoTo ErrHandler

    If Not IsNetworkAvailable() Then
        MsgBox "Network share is not available.", vbExclamation, "Network Unavailable"
        ConsolidateDateRange = ""
        Exit Function
    End If

    If dtEnd < dtStart Then
        MsgBox "End date must be on or after start date.", vbExclamation, "Invalid Range"
        ConsolidateDateRange = ""
        Exit Function
    End If

    ' Create the output workbook
    Dim wbOut As Workbook
    Set wbOut = Workbooks.Add(xlWBATWorksheet)

    Dim wsOut As Worksheet
    Set wsOut = wbOut.Sheets(1)
    wsOut.Name = "ConsolidatedData"

    ' Write headers
    Dim headers As Variant
    headers = Array("S #", "Anesthesiologist", "Site", "Date of Service", _
                    "Shift Name", "On Call", "Shift Type", "Surgical Procedure Code", _
                    "Procedure Start Time", "Procedure Finish Time", "Maximum IC Level", _
                    "Consults", "Fee Modifier 1", "Fee Modifier 2", "Fee Modifier 3", _
                    "Resuscitation", "Obstetrics", "Acute Pain", _
                    "Diagnostic and Chronic Pain", "Miscellaneous Fee Items", _
                    "WCB Number", "Side", "Diagnostic Code", "Injury Code", _
                    "Date of Injury", "Submitted By", "Submitted On", "Source File")

    Dim j As Long
    For j = 0 To UBound(headers)
        wsOut.Cells(1, j + 1).Value = headers(j)
    Next j

    With wsOut.Range(wsOut.Cells(1, 1), wsOut.Cells(1, UBound(headers) + 1))
        .Font.Bold = True
        .Interior.Color = RGB(68, 114, 196)
        .Font.Color = RGB(255, 255, 255)
        .AutoFilter
    End With

    Dim lOutRow As Long
    lOutRow = 2

    Dim lTotalFiles As Long
    lTotalFiles = 0

    Application.ScreenUpdating = False

    ' Loop through each date in the range
    Dim dtCurrent As Date
    For dtCurrent = dtStart To dtEnd
        Application.StatusBar = "Processing " & Format(dtCurrent, "DD/MM/YYYY") & "..."

        Dim colFiles As Collection
        Set colFiles = GetUserFilesForDate(dtCurrent)

        Dim sFile As Variant
        For Each sFile In colFiles
            lTotalFiles = lTotalFiles + 1

            Dim wbIn As Workbook
            Set wbIn = Workbooks.Open(CStr(sFile), ReadOnly:=True, UpdateLinks:=0)

            Dim wsIn As Worksheet
            Set wsIn = wbIn.Sheets(1)

            Dim lastRow As Long
            lastRow = wsIn.Cells(wsIn.Rows.Count, COL_ANESTH).End(xlUp).Row

            Dim i As Long
            For i = 2 To lastRow
                For j = 1 To COL_SUBMON
                    wsOut.Cells(lOutRow, j).Value = wsIn.Cells(i, j).Value
                Next j
                wsOut.Cells(lOutRow, COL_SERIAL).Value = lOutRow - 1

                Dim sFileName As String
                sFileName = Mid(CStr(sFile), InStrRev(CStr(sFile), "\") + 1)
                wsOut.Cells(lOutRow, 28).Value = sFileName

                lOutRow = lOutRow + 1
            Next i

            wbIn.Close SaveChanges:=False
        Next sFile
    Next dtCurrent

    wsOut.Columns.AutoFit

    ' Save
    Dim sOutPath As String
    sOutPath = GetNetworkPath() & FOLDER_DAILY_EXPORTS & "\"
    CreateFolderIfNotExists sOutPath
    sOutPath = sOutPath & "Consolidated_" & Format(dtStart, "YYYYMMDD") & _
               "_to_" & Format(dtEnd, "YYYYMMDD") & ".xlsx"

    Application.DisplayAlerts = False
    wbOut.SaveAs sOutPath, FileFormat:=xlOpenXMLWorkbook
    Application.DisplayAlerts = True

    ' Close the output workbook after saving
    wbOut.Close SaveChanges:=False

    Application.StatusBar = False
    Application.ScreenUpdating = True

    ConsolidateDateRange = sOutPath
    Exit Function

ErrHandler:
    Application.StatusBar = False
    Application.ScreenUpdating = True
    Application.DisplayAlerts = True
    On Error Resume Next
    If Not wbIn Is Nothing Then wbIn.Close SaveChanges:=False
    If Not wbOut Is Nothing Then wbOut.Close SaveChanges:=False
    MsgBox "Error during consolidation: " & Err.Description, vbCritical, "Consolidation Error"
    ConsolidateDateRange = ""
End Function
